import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createCampaign, advanceQuarter, submitPolicy, previewProposal, runLegacy, MODEL_VERSION } from '../src/engine';
import { DATASET_VERSION } from '../src/data/evidence';
import { defaultProposal } from '../src/data/policies';
import type { GameState } from '../src/engine/types';

function finish(state: GameState, quarters = 16) { for (let q = 0; q < quarters && state.phase === 'presidency'; q++) state = advanceQuarter(state).state; return state; }
function output(state: GameState) { return { quarter: state.quarter, realGdp: state.economy.realGDP, growthCagrPercent: ((state.economy.realGDP / state.baseline.nominalGDP) ** (4 / state.quarter) - 1) * 100, inflation: state.economy.inflation, farmerIncomeIndex: state.economy.cocoaFarmerIncome, cocoaThousandTonnes: state.economy.cocoaProduction, cocoaExportsBillionUsd: state.economy.exportsUSD.cocoa, debtToGdpPercent: state.fiscal.debtToGDP, treasuryCashBillionGhs: state.fiscal.cash, policyStatus: state.activePolicies[0]?.status ?? 'none', deliveryPercent: state.activePolicies[0]?.progress ?? 0 }; }
const ensemble = Array.from({ length: 24 }, (_, index) => { const state = finish(createCampaign({ seed: index + 1 })); return { seed: index + 1, ...output(state) }; });
const interventions: { dimension: string; value: number; state: GameState; scale?: number }[] = [];
for (const value of [30, 55, 85]) { const state = createCampaign({ seed: 43 }); state.institutions.administrativeCapacity = value; interventions.push({ dimension: 'administrativeCapacityProxy', value, state }); }
for (const value of [35, 70, 95]) { const state = createCampaign({ seed: 43 }); state.fiscal.debt = state.economy.nominalGDP * value / 100; state.fiscal.debtToGDP = value; state.fiscal.debtService = state.fiscal.debt * state.fiscal.effectiveInterestRate / 4; state.fiscal.balance = state.fiscal.revenue - state.fiscal.baseSpending - state.fiscal.policySpending - state.fiscal.debtService; interventions.push({ dimension: 'openingDebtToGdpPercent', value, state }); }
for (const value of [.25, 1, 2]) interventions.push({ dimension: 'rehabilitationScale', value, state: createCampaign({ seed: 43 }), scale: value });
for (const value of [2500, 4271.9, 7000]) { const state = createCampaign({ seed: 43 }); state.economy.worldCocoaPriceUSD = value; interventions.push({ dimension: 'openingWorldCocoaPriceUsdPerTonne', value, state }); }
const sensitivity = interventions.map(({ dimension, value, state, scale = 1 }) => { const proposal = { ...defaultProposal('cocoa-rehabilitation'), scale }; const preview = previewProposal(state, proposal); const result = finish(preview.valid ? submitPolicy(state, proposal) : state); return { dimension, value, seed: state.seed, policy: proposal.policyId, funding: proposal.funding, previewValid: preview.valid, ...output(result) }; });
const legacy = runLegacy(finish(createCampaign({ seed: 43 })));
const report = { modelVersion: MODEL_VERSION, datasetVersion: DATASET_VERSION, generatedAt: new Date().toISOString(), note: 'Deterministic scenario sensitivity, not estimated causal effects, a statistical interval, or forecast validation. Every intervention is synthetic; seed43 supplies common shocks.', baselineEnsemble: ensemble, sensitivity, legacyEndYears: legacy.map(s => ({ scenario: s.id, ...s.years.at(-1) })), historicalComparison: { source: 'https://www.bog.gov.gh/wp-content/uploads/2026/06/BoG-2025-Annual-Report-and-Financial-Statements-1.pdf', sourceVintage: '2026-06-30', locator: 'Tables 3.1 and 3.3, printed pp44–45', years: [2021, 2022, 2023, 2024, 2025], realGrowthPercent: [5.1, 3.8, 3.1, 5.8, 6], endYearCpiInflationPercent: [12.6, 54.1, 23.2, 23.8, 5.4], caveat: 'Earlier source vintage; July2026 bulletin revises 2024 growth to5.7. No model fitting or backtest claims. The engine inflation ceiling35 cannot reproduce the observed2022 54.1 episode.' } };
await mkdir(resolve('../work'), { recursive: true });
await writeFile(resolve('../work/model-sensitivity.json'), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify({ scenarios: sensitivity.length, baselineSeeds: ensemble.length, fourYearGrowthRangePercent: [Math.min(...ensemble.map(s => s.growthCagrPercent)), Math.max(...ensemble.map(s => s.growthCagrPercent))], report: '../work/model-sensitivity.json' }));
